import type { Metadata } from "next";
import { Montserrat, Lora, Dancing_Script } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});
const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`min-h-screen ${montserrat.variable} ${lora.variable} ${dancingScript.variable} `}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
